name: Deploy to GitHub Pages

on:
  push:
    branches: "main"

defaults:
  run:
    working-directory: ./method1_deepdive

jobs:
  build_site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install elm make
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1

      - name: Install dependencies
        run: |
          pnpm install

      - name: build
        env:
          PUBLIC_BASE_PATH: "/${{ github.event.repository.name }}"
        run: |
          pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: "method1_deepdive/build/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
